### ISSUE TITLE
Search results different from what I see in browser

### ISSUE THREAD

**Issue by chinmayjog13** [joedockrill/jmd_imagescraper#2]
First of all, great repo!

I tried this out, but almost all of the downloaded images are different from the images I see in the browser for a query. What can be the cause for this?
The downloaded images are relevant to the query, just not what I see in the browser

**Comment by joedockrill** [comment]
The default filtering used by the scraper is square layout and only photos. If you try that in the browser you'll probably get more similar results. You can also change the filtering used by the scraper if this isn't what you prefer. 

Some libraries (like the latest fast.ai) may give better results by using rectangular images and using aug cropping to give slightly different square images each time.

**Comment by chinmayjog13** [comment]
Thanks!
