### ISSUE TITLE
Showing "HBox" instead of showing widget for cleaning images

### ISSUE THREAD

**Issue by idhn9999** [joedockrill/jmd_imagescraper#5]
The page https://joedockrill.github.io/jmd_imagescraper/ shows me the following example:

![image](https://user-images.githubusercontent.com/83121503/117576163-6ac58780-b0ed-11eb-8c97-058871d8c16e.png)

But when I try to use it in me notebook from JarvisLabs.ai it shows me the following:

![image](https://user-images.githubusercontent.com/83121503/117576192-92b4eb00-b0ed-11eb-8df6-73981b83a366.png)

What can be the reason here?

**Comment by joedockrill** [comment]
It looks like they don't support jupyter widgets. Talk to them about it.

**Comment by idhn9999** [comment]
thank you
